version: '3'
services:
  webapp:
    build:
    container_name: webapp  # Specify a container name (optional)
    working_dir: /usr/src/app  # Set the working directory in the container
    ports:
      - "3000:3000"  # Map host port 3000 to container port 3000
    environment:
      - NODE_ENV=production
      - DOCKER_BUILDKIT=1
    volumes:
      - ./app:/usr/src/app  # Mount your application code into the container
    command: /usr/src/app/deploy.sh 

  proxy:
    image: nginx
    container_name: proxy
    ports:
      - "80:80"  # Map host port 80 to Nginx container port 80
    volumes:
      - ./htpasswd:/etc/nginx/.htpasswd  # Mount the .htpasswd file
    links:
      - webapp  # Link the proxy to the webapp service
